currentName = two
--

# STAR HERE and create your fist db entry
http://localhost:8000
Content-Type: application/json; charset=utf-8
POST /api/assessment
{"name": "two", "value": 13.012}

# Get the last update to named assessment
http://localhost:8000
Content-Type: application/json; charset=utf-8
GET /api/assessment/:currentName

# Delete by name
http://localhost:8000
Content-Type: application/json; charset=utf-8
DELETE /api/assessment/:currentName

